version: 0.2

env:
  variables:
    REGISTRY_URL: "030787254034.dkr.ecr.ap-northeast-2.amazonaws.com"
#	REGISTRY_NAME: "codebuild-test"
#    TAG: "test1"
#	AWS_REGION: "ap-northeast-2"

phases:

#  pre_build:
#    commands:
#      - echo gradle Build started on `date`
#      - gradlew build -x test
#      - echo gradle Build completed on `date`
    
  build:
    commands:
      - echo ${REGISTRY_URL}
#      - echo Build started on `date`
#      - $(aws ecr get-login --no-include-email --region ap-northeast-2
#      - docker build -t 030787254034.dkr.ecr.ap-northeast-2.amazonaws.com/codebuild-test:test1 .
#      - echo Build completed on `date`
#
#  post_build:
#    commands:
#      - echo Push started on `date`
#      - docker push 030787254034.dkr.ecr.ap-northeast-2.amazonaws.com/codebuild-test:test1
#      - echo Push completed on `date`

#cache:
#  paths:
#    - '/root/.gradle/caches/**/*'

#artifacts: # build result configuration
#  files:
#    - target/demo-0.0.1-SNAPSHOT.jar # build result file name and path
#    - appspec.yml # Spec for CodeDeploy
#    - scripts/*   # Scripts for CodeDeploy
#  discard-paths: no
