version: 0.2

env:
  variables:
    REGISTRY_URL:
    REPOSITORY_NAME:
    TAG:
    AWS_REGION:

phases:

  pre_build:
    commands:
      - echo gradle Build started on `date`
      - chmod 755 gradlew
      - ls -al
      - ./gradlew build -x test
      - echo gradle Build completed on `date`
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - |
          if [ $(aws ecr describe-repositories |grep ${REPOSITORY_NAME} |wc -l) = 0 ];then
            aws ecr create-repository --repository-name ${REPOSITORY_NAME} --image-scanning-configuration scanOnPush=true --region ${AWS_REGION}
          fi

  build:
    commands:
      - echo Build started on `date`
      - docker build -t ${REGISTRY_URL}/${REPOSITORY_NAME}:${TAG} .
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Push started on `date`
      - docker push ${REGISTRY_URL}/${REPOSITORY_NAME}:${TAG}
      - echo Push completed on `date`

cache:
  paths:
    - '/root/.gradle/caches/**/*'

#artifacts: # build result configuration
#  files:
#    - target/demo-0.0.1-SNAPSHOT.jar # build result file name and path
#    - appspec.yml # Spec for CodeDeploy
#    - scripts/*   # Scripts for CodeDeploy
#  discard-paths: no
